### PR TITLE
Fixed performance issue with volume rendering

### PR DESCRIPTION
**Pull request by favreau**

### CODE REVIEW

**Comment by ppodhajski** [comment]
retest this please

**Comment by karjonas** [comment]
Looks good. We should merge #504 first to make sure the unit test still passes with these changes.

**Comment by ppodhajski** [comment]
retest this please

**Comment by ppodhajski** [comment]
retest this please

**Comment by ppodhajski** [comment]
retest this please

**Comment by ppodhajski** [comment]
retest this please

**Pull request merged**
