### PR TITLE
Test fix

### PR DESCRIPTION
**Pull request by ppodhajski**

### CODE REVIEW

**Comment by ppodhajski** [comment]
retest this please

**Comment by ppodhajski** [comment]
retest this please

**Comment by ppodhajski** [comment]
retest this please

**Comment by ppodhajski** [comment]
retest this please

**Comment by ppodhajski** [comment]
retest this please

**Comment by tribal-tec** [comment]
Fixed with https://github.com/BlueBrain/Brayns/pull/782

**Pull request closed without merging**
