### PR TITLE
Fixed some typo's

### PR DESCRIPTION
**Pull request by Helveg**
Lacking any other relevant knowledge, I contribute some typo fixes in the docs.

### CODE REVIEW

**Comment by NadirRoGue** [comment]
Hello @Helveg 

Thank you for the patch, everything seems correct.

Although not stated in the documentation, we follow a specific git workflow in which we add features and fixes to the branch `develop`. Then, prior only to a release, we make a PR from `develop` to `master`. Could you switch your PR to point to `develop` branch, in order to keep this workflow?

Thank you again!

**Comment by Helveg** [comment]
Ok, I rebased onto `develop` and updated the PR base here on GitHub

**Review by NadirRoGue — APPROVED** [review]

**Comment by NadirRoGue** [comment]
Approved, you may proceed to squash and merge

**Comment by Helveg** [comment]
Someone with write access will have to do so :)

**Pull request merged**
