### PR TITLE
Mooc preparation

### PR DESCRIPTION
**Pull request by NadirRoGue**

### CODE REVIEW

**Comment by ppodhajski** [comment]
retest this please

**Comment by ppodhajski** [comment]
retest this please

**Comment by ppodhajski** [comment]
retest this please

**Comment by ppodhajski** [comment]
retest this please

**Comment by ppodhajski** [comment]
retest this please

**Comment by ppodhajski** [comment]
retest this please

**Review by chevtche — APPROVED** [review]

**Pull request merged**
