### PR TITLE
Add PBR shading for Optix

### PR DESCRIPTION
**Pull request by chevtche**
- Add anisotropic texture filtering with ray differential
- Add automatic mipmaps generation
- Support for mipmap loading from file
- Fix textures loading (alpha channel and vertical flip)
- Use of optix's textures ids
- Add radiance and irradiance computation of env maps

### CODE REVIEW

**Comment by ppodhajski** [comment]
retest this please

**Comment by tribal-tec** [comment]
retest this please

**Comment by ppodhajski** [comment]
retest this please

**Comment by ppodhajski** [comment]
retest this please

**Comment by ppodhajski** [comment]
retest this please

**Comment by ppodhajski** [comment]
retest this please

**Comment by ppodhajski** [comment]
retest this please

**Comment by ppodhajski** [comment]
retest this please

**Comment by ppodhajski** [comment]
retest this please

**Comment by ppodhajski** [comment]
retest this please

**Comment by ppodhajski** [comment]
retest this please

**Comment by ppodhajski** [comment]
retest this please

**Comment by ppodhajski** [comment]
retest this please

**Pull request merged**
