### PR TITLE
Brayns 316 remove assimp

### PR DESCRIPTION
**Pull request by Adrien4193**
Assimp replaced by custom mesh parsers (no libraries).

Supports files OBJ, PLY, STL and OFF.

No materials extracted, just a default white one for the whole mesh.

No triangulation (only supports triangular faces).

Vertex duplication for all formats (vertex count = 3 * index count).

An OBJ file can contain multiple objects.

A PLY file can have position, normal, color and texture coordinates (vertex + face) in vertices.

STL complete support.

Only positions supported in OFF files.

### CODE REVIEW

**Comment by Adrien4193** [comment]
retest this please

**Comment by Adrien4193** [comment]
retest this please

**Comment by Adrien4193** [comment]
retest this please

**Comment by Adrien4193** [comment]
retest this please

**Comment by Adrien4193** [comment]
retest this please

**Comment by NadirRoGue** [comment]
retest this please

**Comment by Adrien4193** [comment]
retest this please

**Comment by Adrien4193** [comment]
retest this please

**Comment by Adrien4193** [comment]
retest this please

**Comment by Adrien4193** [comment]
retest this please

**Comment by Adrien4193** [comment]
retest this please

**Comment by Adrien4193** [comment]
retest this please

**Comment by Adrien4193** [comment]
retest this please

**Comment by Adrien4193** [comment]
retest this please

**Comment by Adrien4193** [comment]
retest this please

**Comment by Adrien4193** [comment]
retest this please

**Comment by Adrien4193** [comment]
retest this please

**Comment by Adrien4193** [comment]
retest this please

**Comment by Adrien4193** [comment]
retest this please

**Comment by Adrien4193** [comment]
retest this please

**Comment by Adrien4193** [comment]
retest this please

**Comment by Adrien4193** [comment]
retest this please

**Comment by Adrien4193** [comment]
retest this please

**Comment by Adrien4193** [comment]
retest this please

**Comment by NadirRoGue** [comment]
retest this please

**Pull request closed without merging**
