### PR TITLE
Improve README

### PR DESCRIPTION
**Pull request by karjonas**
Ubuntu 18.04 dependencies

OptiX installation

### CODE REVIEW

**Comment by ppodhajski** [comment]
retest this please

**Comment by karjonas** [comment]
retest this please

**Comment by ppodhajski** [comment]
retest this please

**Comment by ppodhajski** [comment]
retest this please

**Comment by ppodhajski** [comment]
retest this please

**Comment by ppodhajski** [comment]
retest this please

**Pull request merged**
