### PR TITLE
Fixed docker build

### PR DESCRIPTION
**Pull request by favreau**

### CODE REVIEW

**Comment by favreau** [comment]
if you docker run the image (docker run -ti --rm -p 8200:8200 brayns) and open a brower on http://localhost:8000/registry, you should see the HTTP REST API exposed by brayns.
`{
   "v1/camera" : [ "GET", "PUT" ],
   "v1/camera/schema" : [ "GET" ],
   "v1/circuit-config-builder" : [ "GET" ],
   "v1/clip-planes" : [ "GET", "PUT" ],
   "v1/clip-planes/schema" : [ "GET" ],
   "v1/data-source" : [ "GET", "PUT" ],
   "v1/data-source/schema" : [ "GET" ],
   "v1/force-rendering" : [ "GET", "PUT" ],
   "v1/force-rendering/schema" : [ "GET" ],
   "v1/frame" : [ "GET", "PUT" ],
   "v1/frame-buffers" : [ "GET" ],
   "v1/frame-buffers/schema" : [ "GET" ],
   "v1/frame/schema" : [ "GET" ],
   "v1/image-jpeg" : [ "GET" ],
   "v1/image-jpeg/schema" : [ "GET" ],
   "v1/material-lut" : [ "GET", "PUT" ],
   "v1/material-lut/schema" : [ "GET" ],
   "v1/progress" : [ "GET" ],
   "v1/progress/schema" : [ "GET" ],
   "v1/reset-camera" : [ "PUT" ],
   "v1/reset-camera/schema" : [ "GET" ],
   "v1/scene" : [ "GET", "PUT" ],
   "v1/scene/schema" : [ "GET" ],
   "v1/settings" : [ "GET", "PUT" ],
   "v1/settings/schema" : [ "GET" ],
   "v1/simulation-histogram" : [ "GET" ],
   "v1/simulation-histogram/schema" : [ "GET" ],
   "v1/spikes" : [ "GET", "PUT" ],
   "v1/spikes/schema" : [ "GET" ],
   "v1/stream" : [ "GET", "PUT" ],
   "v1/stream-to" : [ "PUT" ],
   "v1/stream-to/schema" : [ "GET" ],
   "v1/stream/schema" : [ "GET" ],
   "v1/version" : [ "GET" ],
   "v1/version/schema" : [ "GET" ],
   "v1/viewport" : [ "GET", "PUT" ],
   "v1/viewport/schema" : [ "GET" ],
   "v1/volume-histogram" : [ "GET" ],
   "v1/volume-histogram/schema" : [ "GET" ]
}`

**Comment by favreau** [comment]
I double-checked the image and it's now fine. Two runtime dependencies were missing. If you are happy with that, can you approve? Thanks :)

**Comment by tristan0x** [comment]
Hey @favreau 
This pull-request must be reviewed by somebody having write access to be merged.
My approval is not worth a penny!

**Comment by favreau** [comment]
@ tristan0x, I just added you. You should be able to approve. Your approval counts!

**Pull request merged**
