### PR TITLE
Add shorthand for using OSPRay engine

### PR DESCRIPTION
**Pull request by karjonas**

### CODE REVIEW

**Comment by tribal-tec** [comment]
shorthand? shortcut?

**Comment by karjonas** [comment]
Yes. For symmetry it is convenient to be able to call both OSPRay and OptiX with ```--engine ospray/optix``` instead of ```--engine braynsOSPRayEngine/braynsOptiXEngine```.

**Comment by tribal-tec** [comment]
no, I was wondering why the word `shorthand`, where you probably meant `shortcut`? Shorthand to me means stenography.

**Comment by karjonas** [comment]
Shorthand has several meanings :)

**Comment by karjonas** [comment]
retest this please

**Pull request merged**
