### PR TITLE
Cleanups after introduction of models

### PR DESCRIPTION
**Pull request by tribal-tec**

### CODE REVIEW

**Comment by tribal-tec** [comment]
retest this please

**Comment by tribal-tec** [comment]
retest this please

**Comment by tribal-tec** [comment]
retest this please

**Comment by tribal-tec** [comment]
retest this please

**Comment by favreau** [comment]
retest this please

**Comment by favreau** [comment]
retest this please

**Comment by favreau** [comment]
Retest this please

**Comment by tribal-tec** [comment]
don't merge yet!!!

**Comment by tribal-tec** [comment]
Retest this please

**Comment by tribal-tec** [comment]
Retest this please

**Comment by tribal-tec** [comment]
Retest this please

**Pull request merged**
