### PR TITLE
Moved performance tests to dedicated folder

### PR DESCRIPTION
**Pull request by favreau**

### CODE REVIEW

**Comment by favreau** [comment]
Retest this please

**Comment by hernando** [comment]
If the test is in a directory called perf you don't need to prefix its name by perf.

**Comment by favreau** [comment]
Yes, I remember that, but that still makes sense to start the name of the file with perf.

**Comment by hernando** [comment]
For me it's redundant.

**Comment by favreau** [comment]
Renamed perfBrayns.cpp to renderingSettings.cpp

**Pull request merged**
