### PR TITLE
Fix for full morphology spike report simulation rendering

### PR DESCRIPTION
**Pull request by NadirRoGue**

### CODE REVIEW

**Comment by ppodhajski** [comment]
> -- Not configured brain.py: Boost.Python, Python or Numpy not found

**Comment by NadirRoGue** [comment]
This comes from Brion, not Brayns, and is not related to the patch itself at all, so that must have been there for a long time. Python bindings for Brion when linking to Brayns have no use, so for me is fine they are not build whatsoever.

**Comment by NadirRoGue** [comment]
Moreover, this branch is using Brion at commit 70b32bf8f79ff5852c4d1fb7b2a4b4051043f579, which does not include the cmake python fixes applied at cd590fee91c24b48c5aa357577c9eed3e836b7d9. Before this commit, the python 3 libraries where not setted when building using cmake > 3.12, which explains this message.

**Comment by NadirRoGue** [comment]
retest this please

**Comment by NadirRoGue** [comment]
retest this please

**Comment by NadirRoGue** [comment]
retest this please

**Comment by ppodhajski** [comment]
retest this please

**Comment by ppodhajski** [comment]
retest this please

**Comment by ppodhajski** [comment]
retest this please

**Comment by ppodhajski** [comment]
retest this please

**Comment by ppodhajski** [comment]
retest this please

**Comment by ppodhajski** [comment]
retest this please

**Comment by ppodhajski** [comment]
retest this please

**Comment by ppodhajski** [comment]
retest this please

**Comment by ppodhajski** [comment]
retest this please

**Comment by ppodhajski** [comment]
retest this please

**Comment by ppodhajski** [comment]
retest this please

**Comment by ppodhajski** [comment]
retest this please

**Comment by ppodhajski** [comment]
retest this please

**Comment by ppodhajski** [comment]
retest this please

**Comment by ppodhajski** [comment]
retest this please

**Comment by ppodhajski** [comment]
retest this please

**Review by ppodhajski — APPROVED** [review]

**Pull request merged**
