### PR TITLE
Fixed transform issue with scaling. For more details, see: https://to…

### PR DESCRIPTION
**Pull request by tolokoban**
For more details, see: [https://tokoban.github.io/web-brayns/rotation-center.html](https://tokoban.github.io/web-brayns/rotation-center.html)

Now, place a model into the space, you will give :
* its scale,
* the location where you want to find it if no rotation occurs,
* the rotation center,
* the quaternion of rotation around that center.

Then, if you want your model to rotate around its own center, you must set the __rotation center__ to be equal to the __location__.

### CODE REVIEW

**Comment by favreau** [comment]
Thanks for the PR. But do not merge until this is validated with the Plugins, mainly the molecular systems. This will have impact on the loading of the current notebooks, and the scenes that I am currently working on.

**Comment by tolokoban** [comment]
Hi Cyrille!
Did you get a chance to test this change against your Molecular System plugin?

**Comment by favreau** [comment]
Looks good to me.

**Comment by tolokoban** [comment]
This fix has already been merged in Nadir's branch.

**Pull request merged**
