### PR TITLE
1.1.0 Release preparation

### PR DESCRIPTION
**Pull request by NadirRoGue**

### CODE REVIEW

**Review by chevtche — DISMISSED** [review]

**Comment by ppodhajski** [comment]
python plans say:
> Exception: Brayns does not satisfy minimal required version; needed 1.1.0, got 1.0.1

**Comment by NadirRoGue** [comment]
retest this please

**Comment by NadirRoGue** [comment]
> python plans say:
> 
> > Exception: Brayns does not satisfy minimal required version; needed 1.1.0, got 1.0.1

fixed

**Comment by ppodhajski** [comment]
python/doc/source/metadata.json to be updated as well?

**Comment by NadirRoGue** [comment]
> python/doc/source/metadata.json to be updated as well?

updated, thanks.

**Review by ppodhajski — APPROVED** [review]

**Comment by ppodhajski** [comment]
@chevtche  ?

**Review by chevtche — APPROVED** [review]

**Comment by chevtche** [comment]
Don't have any additional comments. Approved.

**Pull request merged**
